module.exports.onReady = require('./ready')
module.exports.onMessage = require('./message')
module.exports.onError = require('./error')
module.exports.onMessageReactionAdd = require('./messageReactionAdd')
module.exports.onMessageReactionRemove = require('./messageReactionRemove')